### ISSUE TITLE
Minecraft crashes when setting galactic craft screen

### ISSUE THREAD

**Issue by DonnerTechQ2** [igentuman/GalacticResearch#22]
If i remove galactic research, the screen works fine

```
Description: Rendering Block Entity

java.lang.IndexOutOfBoundsException: Index: 8, Size: 8
    at java.util.ArrayList.rangeCheck(ArrayList.java:659)
    at java.util.ArrayList.get(ArrayList.java:435)
    at micdoodle8.mods.galacticraft.api.GalacticraftRegistry.getGameScreen(GalacticraftRegistry.java:359)
    at micdoodle8.mods.galacticraft.core.client.screen.DrawGameScreen.doDraw(DrawGameScreen.java:198)
    at micdoodle8.mods.galacticraft.core.client.screen.DrawGameScreen.drawScreen(DrawGameScreen.java:108)
    at micdoodle8.mods.galacticraft.core.client.render.tile.TileEntityScreenRenderer.render(TileEntityScreenRenderer.java:104)
    at micdoodle8.mods.galacticraft.core.client.render.tile.TileEntityScreenRenderer.func_192841_a(TileEntityScreenRenderer.java:22)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_192854_a(TileEntityRendererDispatcher.java:201)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(TileEntityRendererDispatcher.java:157)
    at net.minecraft.client.renderer.RenderGlobal.redirect$zbh000$tileEntityRender(RenderGlobal.java:3783)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:1031)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1808)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1621)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1390)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```
```

-- Block Entity Details --
  Name: galacticraftcore:gc_view_screen // micdoodle8.mods.galacticraft.core.tile.TileEntityScreen
  Block type: ID #421 (tile.view_screen // micdoodle8.mods.galacticraft.core.blocks.BlockScreen // galacticraftcore:view_screen)
  Block data value: 4 / 0x4 / 0b0100
  Block location: World: (-20,65,812), Chunk: (at 12,4,12 in -2,50; contains blocks -32,0,800 to -17,255,815), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
  Actual block type: ID #421 (tile.view_screen // micdoodle8.mods.galacticraft.core.blocks.BlockScreen // galacticraftcore:view_screen)
  Actual block data value: 4 / 0x4 / 0b0100
  Block Entity NBT: {connectionsRight:0,connectionsDown:0,x:-20,y:65,connectionsUp:1,multiscreen:1b,z:812,connectionsLeft:1,id:"galacticraftcore:gc_view_screen",type:8}
```

**Comment by igentuman** [comment]
What mod version do you have? This one pretty much looks like that issue i fixed before

**Comment by DonnerTechQ2** [comment]
> What mod version do you have? This one pretty much looks like that issue i fixed before

GalacticResearch-1.0.4
