### ISSUE TITLE
[CRASH] Unconfirmed crash.

### ISSUE THREAD

**Issue by reverentfeynmen** [igentuman/GalacticResearch#25]
![Screenshot 2024-05-23 165806](https://github.com/igentuman/GalacticResearch/assets/166317640/ecc01830-bccb-4418-9a5e-1c0537c88c69)
---- Minecraft Crash Report ----

WARNING: coremods are present:
  TransformerLoader (OpenComputers-MC1.12.2-1.8.5+179e1c3.jar)
  GSHooksLoader (GalaxySpace-1.12.2-2.1.3.jar)
  ReflectorsPlugin (GalacticResearch-1.1.2.jar)
  MicdoodlePlugin (Galacticraft-1.12.2-4.0.6.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 5/23/24 4:56 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/mjr/extraplanets/api/event/CustomCelestialGUIEvent$PreLoadingGalaxies
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:612)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:595)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: com/mjr/extraplanets/api/event/CustomCelestialGUIEvent$PreLoadingGalaxies
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:82)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:82)
	... 37 more
Caused by: java.lang.ClassNotFoundException: com.mjr.extraplanets.api.event.CustomCelestialGUIEvent$PreLoadingGalaxies
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 45 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 738157200 bytes (703 MB) / 1133510656 bytes (1081 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 26 mods loaded, 26 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version      | Source                                   | Signature                                |
	|:----- |:-------------------- |:------------ |:---------------------------------------- |:---------------------------------------- |
	| LC    | minecraft            | 1.12.2       | minecraft.jar                            | None                                     |
	| LC    | mcp                  | 9.42         | minecraft.jar                            | None                                     |
	| LC    | FML                  | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | micdoodlecore        | 4.0.6        | minecraft.jar                            | None                                     |
	| LC    | opencomputers|core   | 1.8.5        | minecraft.jar                            | None                                     |
	| LC    | galacticraftcore     | 4.0.6        | Galacticraft-1.12.2-4.0.6.jar            | None                                     |
	| LC    | galacticraftplanets  | 4.0.6        | Galacticraft-1.12.2-4.0.6.jar            | None                                     |
	| LC    | addtlplanets         | 1.0.0        | 1.12.2-A.0.3.jar                         | None                                     |
	| LC    | asmodeuscore         | 1.0.1        | AsmodeusCore-1.12.2-1.0.1.jar            | None                                     |
	| LC    | crafttweaker         | 4.1.20       | CraftTweaker2-1.12-4.1.20.699.jar        | None                                     |
	| LC    | ctgui                | 1.0.0        | CraftTweaker2-1.12-4.1.20.699.jar        | None                                     |
	| LC    | jei                  | 4.16.1.301   | jei_1.12.2-4.16.1.301.jar                | None                                     |
	| LC    | crafttweakerjei      | 2.0.3        | CraftTweaker2-1.12-4.1.20.699.jar        | None                                     |
	| LC    | galaxyspace          | 2.1.3        | GalaxySpace-1.12.2-2.1.3.jar             | None                                     |
	| LC    | opencomputers        | 1.8.5        | OpenComputers-MC1.12.2-1.8.5+179e1c3.jar | None                                     |
	| LC    | galacticcomputers    | 1.0.0        | GalacticComputers-1.0.0.jar              | None                                     |
	| LC    | gc-rpc               | 2.2.0        | galacticraft-rpc-2.2.0.jar               | None                                     |
	| LC    | galacticrafttweaker  | 1.12.2-1.0.3 | GalacticraftTweaker-1.12.2-1.0.3.jar     | b02331787272ec3515ebe63ecdeea0d746653468 |
	| LE    | galacticresearch     | 1.0.0        | GalacticResearch-1.1.2.jar               | None                                     |
	| L     | exoplanets           | 0.1.4        | Interstellar-Exoplanets-0.1.4.jar        | None                                     |
	| L     | nasatweaker          | 1.0.1        | nasatweaker-1.0.1.jar                    | None                                     |
	| L     | spaceambient         | 0.0.1        | SpaceAmbient-1.12.2-0.0.1.jar            | None                                     |
	| L     | spaceastronomytweaks | 1.12.2-0.2   | SpaceAstronomyTweaks-1.12.2-0.2.jar      | None                                     |
	| L     | spacex               | 1.12.2       | SpaceCraftX-1.2.1.jar                    | None                                     |
	| L     | galactictweaks       | ${version}   | GalacticTweaks-1.8.0.jar                 | None                                     |

	Loaded coremods (and transformers): 
TransformerLoader (OpenComputers-MC1.12.2-1.8.5+179e1c3.jar)
  li.cil.oc.common.asm.ClassTransformer
GSHooksLoader (GalaxySpace-1.12.2-2.1.3.jar)
  galaxyspace.core.hooklib.minecraft.PrimaryClassTransformer
ReflectorsPlugin (GalacticResearch-1.1.2.jar)
  igentuman.galacticresearch.reflection.ReflectorsPlugin
MicdoodlePlugin (Galacticraft-1.12.2-4.0.6.jar)
  micdoodle8.mods.miccore.MicdoodleTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 551.61' Renderer: 'NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2'

**Comment by igentuman** [comment]
You don't have extra planets?
